/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '110018945' at '16/03/16 13:08' with Gradle 2.11
 *
 * @author 110018945, @date 16/03/16 13:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
